"""The Quest Log's Key Items chapter: every key item the game hands out, in roughly the order the story does.

Each row: (item id, flag, name, hint, where).
  flag   0, or a flag that proves you got it even after the item is gone from the Bag (given away, used up,
         taken back) - the script's own "received" flag, or the pickup's object flag. A row is ticked when the
         item is in the Bag or this flag is set.
  hint   not shown in game any more (key item names are always shown, so A gives "where" straight away);
         kept as a short summary.
  where  what A shows: where the item comes from.
Sources are the game's scripts (tools/romdata/scripts.py now indexes giveitem: copyvarifnotzero 0x8000). Items
in the Key Items pocket with no source in any script are left out: the FireRed leftovers (Oak's Parcel, Poké
Flute, Secret Key, Bike Voucher, Card Key, Lift Key, Silph Scope, Bicycle, VS Seeker, TM Case, Berry Pouch,
Teachy TV, Tri-Pass, Rainbow Pass, Tea, Ruby, Sapphire, Gold Teeth), the Abandoned Ship's room keys, Red Orb 2,
Blue Orb 2, the Wishing Chip and item 644 (still a Chinese name).
"""

KEYITEMS = [
    # ---- Hoenn
    (363, 0, "Journal", "It finds you on its own, at the start of your journey.",
     "Handed to you automatically. Use it (or R in the Start menu) for this Quest Log."),
    (361, 0, "Sinnoh Map", "It finds you on its own, at the start of your journey.",
     "Handed to you automatically. A on a town you have reached flies you there."),
    (269, 0x008F, "Devon Goods", "Something stolen near Rustboro City.",
     "Taken back from the Team Aqua grunt in Rusturf Tunnel, then delivered to Capt. Stern in Slateport City."),
    (274, 0x00BC, "Letter", "The president of a Rustboro company needs a favour.",
     "From Mr. Stone at Devon Corp., Rustboro City, for Steven in Granite Cave."),
    (262, 0, "Old Rod", "A fisherman in a small island town.",
     "From the fisherman in Dewford Town."),
    (120, 0, "Mega Bracelet", "A trainer who loves rare stones, on a route east of Mauville.",
     "From Steven on Route 118. (Zinnia borrows it later and gives it back.)"),
    (271, 0, "Basement Key", "A Gym Leader in Mauville City needs a favour.",
     "From Wattson in Mauville City, for New Mauville."),
    (259, 0, "Mach Bike", "A cycle shop in Mauville City.",
     "From Rydel at the cycle shop in Mauville City. This game gives both bikes."),
    (272, 0, "Acro Bike", "A cycle shop in Mauville City.",
     "From Rydel at the cycle shop in Mauville City. This game gives both bikes."),
    (260, 0, "Coin Case", "Someone in Mauville City wants a certain kind of mail.",
     "Traded for Harbor Mail in a house in Mauville City."),
    (268, 0, "Wailmer Pail", "A flower shop on a route near Petalburg Woods.",
     "From the Pretty Petal flower shop on Route 104."),
    (261, 0, "Itemfinder", "Your rival, after a battle on a route with a cycling road.",
     "From your rival after your battle on Route 110."),
    (279, 0, "Go-Goggles", "Your rival, in a hot-spring town.",
     "From your rival in Lavaridge Town, after the Lavaridge Gym."),
    (270, 0, "Soot Sack", "A glassworker on an ash-covered route.",
     "From the glassworker's house on Route 113."),
    (263, 0, "Good Rod", "A fisherman on a route east of Mauville.",
     "From the fisherman on Route 118."),
    (734, 0, "Ride Pager", "Your rival, on a long rainy route.",
     "From your rival after your battle on Route 119. It replaces Fly."),
    (288, 0, "Devon Scope", "A trainer who loves rare stones, near Fortree City.",
     "From Steven on Route 120, where something invisible blocks the way."),
    (280, 0x0073, "Meteorite", "A machine on top of a volcano.",
     "Taken off Team Magma's machine on Mt. Chimney."),
    (375, 0, "Magma Emblem", "The summit of a mountain of graves, after the teams have been.",
     "From the old woman at the summit of Mt. Pyre."),
    (273, 0, "Pokéblock Case", "A contest hall in a seaside city.",
     "From the Contest Hall reception in Lilycove City."),
    (266, 0, "Contest Pass", "A contest hall in a seaside city.",
     "From the Contest Hall reception in Lilycove City."),
    (372, 0, "Powder Jar", "Someone in a port city talks about Berries and medicine.",
     "From the man in Slateport City who talks about Berry Powder."),
    (264, 0, "Super Rod", "A fisherman in a city by the space center.",
     "From the fisherman in Mossdeep City."),
    (285, 0x044C, "Storage Key", "Deep inside a wrecked ship.",
     "Lying in the Abandoned Ship. It opens the storage room, and stays in the door."),
    (278, 0x0436, "Scanner", "Deep inside a wrecked ship, by a strange stone pillar.",
     "The strange stone pillar in the Abandoned Ship."),
    (695, 0, "News Tracker", "Two TV reporters looking for strong trainers.",
     "From Gabby and Ty, who wait on Routes 111, 118 and 120."),
    (119, 0x4022, "Shiny Charm", "It lies somewhere on a route east of Mauville.",
     "Lying on the west side of Route 118."),
    (265, 0, "S.S. Ticket", "Home, after you have become Champion.",
     "From your Dad at home in Littleroot Town after the Pokémon League."),
    # ---- Post-game
    (275, 0, "Eon Ticket", "A ticket for Lilycove's port, from the Mystery Gift counter.",
     "From the Mystery Gift attendant upstairs in a Pokémon Center, or Mr. Steven's aide on Steven's Island."),
    (376, 0, "Old Sea Map", "Mr. Steven leaves something for you on his island.",
     "From Mr. Steven's aide on Steven's Island, with the Eon Ticket."),
    (694, 0, "Ultimate Book", "A visitor from Ultra Space on Steven's Island.",
     "From the Ultimate Investigator on Steven's Island. It records where the Ultra Wormholes open."),
    (696, 0, "Travel Suit", "A visitor from Ultra Space on Steven's Island.",
     "From the Ultimate Investigator on Steven's Island, for travelling through wormholes."),
    (622, 0, "Z-Power Ring", "An island trial with a Kahuna.",
     "From Nanu on Strange Island, after Tapu Bulu's trial."),
    (247, 0x4191, "Special Gem", "An island lost in time and space.",
     "Lying on Remote Island."),
    (641, 0x430E, "N-Solarizer", "The far side of an Ultra Wormhole, where the light was stolen.",
     "Lying in Ultra Space Zero. Faba also hands the pair over at Rainbow Castle."),
    (642, 0x430E, "N-Lunarizer", "The far side of an Ultra Wormhole, where the light was stolen.",
     "Lying in Ultra Space Zero. Faba also hands the pair over at Rainbow Castle."),
    (621, 0x03EF, "Zygarde Cube", "Hoenn: a route with a cycling road; also a Kalos cave.",
     "Lying on Route 110 (also in Terminus Cave)."),
    (616, 0x4039, "Rotom Catalog", "Hoenn: a power plant hidden underground.",
     "In New Mauville."),
    (671, 0x404E, "DNA Splicers", "Unova: an ice-cold chasm.",
     "In Giant Chasm, after Ghetsis."),
    (672, 0x404B, "Gracidea", "A paradise of flowers.",
     "In Flower Paradise."),
    (673, 0x4053, "Prison Bottle", "The deepest part of a wrecked ship.",
     "In the depths of the Abandoned Ship."),
    (543, 0x4054, "Deoxys Meteor", "A temple of the people who came from the stars.",
     "At the Meteor Temple."),
    (650, 0, "EV-IV Display", "A rival who trains without mercy, in a tree-top city.",
     "From Paul after your rematch in Fortree City."),
    (54, 0, "Dark Scroll", "A Battle Tower leader from Sinnoh visits the Battle Frontier.",
     "From Palmer at the Battle Frontier, after 35 wins in a row at the Battle Tower (Dark or Water Scroll)."),
    (55, 0, "Water Scroll", "A Battle Tower leader from Sinnoh visits the Battle Frontier.",
     "From Palmer at the Battle Frontier, after 35 wins in a row at the Battle Tower (Dark or Water Scroll)."),
    (371, 0, "AuroraTicket", "The Battle Frontier's owner, once you earn a Silver Symbol.",
     "From Scott in his Battle Frontier house, with your first Silver Symbol - e.g. the Ability Symbol from "
     "Salon Maiden Anabel at the Battle Tower. It takes you to Champion Island."),
    (699, 0, "Endorsement", "The Battle Frontier's owner, once you earn a Silver Symbol.",
     "From Scott in his Battle Frontier house, with your first Silver Symbol - e.g. the Ability Symbol from "
     "Salon Maiden Anabel at the Battle Tower."),
    (370, 0, "MysticTicket", "A girl from Johto, lost in Hoenn.",
     "From Lyra once you give her directions (Route 102, later the Bell Tower)."),
    (701, 0, "Dynamax Band", "An island where the world's best trainers meet.",
     "From Leon's friend on Champion Island. (Yanshan also lends one, then takes it back.)"),
    (742, 0, "Unity Reins", "A shrine of a crowned king.",
     "From the attendant at the Crown Shrine."),
    (182, 0, "Exp. Share", "Watch a vision of the end of the world.",
     "Given after Arceus's vision in the Unown Ruins (also shown in Amity Square)."),
    (674, 0, "Reveal Glass", "A trainer from Unova searching for N.",
     "From Hilda (Route 116, later Celestic Town)."),
    # ---- Sinnoh and Hisui
    (768, 0x4324, "Sinnoh Pager", "Sinnoh: a city with a great department store.",
     "Lying in Veilstone City."),
    (744, 0x4322, "Dried Fish", "Hisui, for a hungry cat.",
     "Lying in Hisui. Kitty on Steven's Island wants it."),
    (745, 0, "UnnamedStone", "A cat on Steven's Island, once she has eaten.",
     "From Kitty on Steven's Island, for the Dried Fish."),
]

assert len({i for i, *_ in KEYITEMS}) == len(KEYITEMS)
