"""The Quest Log's Legends chapter: every legendary and mythical Pokemon in the game, by National Dex number.
Ultra Beasts are in too, counted as mythical (Blacephalon is not in the game).

Each row: (national dex no., name, hint, where).
  hint   shown while the Pokemon is not in your Pokedex yet (the row reads "???"): where to look, no name.
  where  shown once it is seen or caught: the place, the level, and what it takes.
Places and levels are read from the game's scripts (tools/romdata: scripts.py, flag_audit.py). Gen 9 legends
(Treasures of Ruin, Koraidon, Miraidon, the Loyal Three, Ogerpon, Terapagos, Pecharunt) are not in the game.
Both texts use the Journal's wording rule: no names of what you have not met.
"""

LEGENDS = [
    (144, "Articuno", "A legendary bird nests on a sacred island far from Hoenn's shores.",
     "Navel Rock, Lv50, with the other two legendary birds. The three also appear together on Route 128 (Lv40)."),
    (145, "Zapdos", "A legendary bird nests on a sacred island far from Hoenn's shores.",
     "Navel Rock, Lv50, with the other two legendary birds. The three also appear together on Route 128 (Lv40)."),
    (146, "Moltres", "A legendary bird nests on a sacred island far from Hoenn's shores.",
     "Navel Rock, Lv50, with the other two legendary birds. The three also appear together on Route 128 (Lv40)."),
    (150, "Mewtwo", "Deep in a cave of Kanto, past the ones who guard it.",
     "Cerulean Cave, Lv50, at the far end past the Team Rocket executives."),
    (151, "Mew", "An island that is on no map. An old sea chart shows the way.",
     "Faraway Island, Lv30. Sail there from Lilycove City with the Old Sea Map."),
    (243, "Raikou", "Johto: the ruins of a burned tower.",
     "The Bell Tower Ruins in Johto, Lv50, with Entei and Suicune. Also met at Navel Rock."),
    (244, "Entei", "Johto: the ruins of a burned tower.",
     "The Bell Tower Ruins in Johto, Lv50, with Raikou and Suicune. Also met at Navel Rock."),
    (245, "Suicune", "Johto: the ruins of a burned tower.",
     "The Bell Tower Ruins in Johto, Lv50, with Raikou and Entei."),
    (249, "Lugia", "Johto: deep inside a group of islands in a whirling sea.",
     "The depths of the Whirl Islands in Johto. Dark Lugia (Lv70), met on the Abandoned Ship, also counts."),
    (250, "Ho-Oh", "Johto: the top of a tall bell-ringing tower.",
     "The summit of the Bell Tower in Johto, after the legendary birds. It also appears at Navel Rock."),
    (251, "Celebi", "A forest where time does not flow as it should.",
     "Timeless Woods, Lv30."),
    (377, "Regirock", "Hoenn: ancient ruins in the desert, sealed by an old puzzle.",
     "Desert Ruins (Route 111), Lv40, once the Sealed Chamber's Braille puzzle is solved."),
    (378, "Regice", "Hoenn: a cave on a small island, sealed by an old puzzle.",
     "Island Cave (Route 105), Lv40, once the Sealed Chamber's Braille puzzle is solved."),
    (379, "Registeel", "Hoenn: an ancient tomb on a route, sealed by an old puzzle.",
     "Ancient Tomb (Route 120), Lv40, once the Sealed Chamber's Braille puzzle is solved."),
    (380, "Latias", "Hoenn: a small southern island. It visits in dreams.",
     "Southern Island, where the stone reads \"All dreams are but another reality\"."),
    (381, "Latios", "Hoenn: a small southern island. It visits in dreams.",
     "Southern Island, where the stone reads \"All dreams are but another reality\"."),
    (382, "Kyogre", "Hoenn: a cave beneath the sea that opens only in heavy rain.",
     "Marine Cave, Lv70, under the sea around Route 125."),
    (383, "Groudon", "Hoenn: a cave that opens only under harsh sunlight.",
     "Terra Cave, Lv70, off Route 115."),
    (384, "Rayquaza", "Hoenn: the top of a tower rising from the sea.",
     "Sky Pillar, Lv50, at the top (the Delta Episode; a Mach Bike is needed inside)."),
    (385, "Jirachi", "Hoenn: the deepest cave of the Battle Frontier's coast.",
     "Artisan Cave, Lv30. The same event is also set up in Mossdeep City."),
    (386, "Deoxys", "An island out beyond the sea, with a triangle-shaped puzzle.",
     "Birth Island (the map is named Outer Space), Lv50."),
    (480, "Uxie", "Sinnoh: the lake in the snowy north.",
     "Lake Acuity, Lv50. Also in the Test of Heart caves."),
    (481, "Mesprit", "Sinnoh: the lake near where the journey there begins.",
     "Lake Verity, Lv50. Also in the Test of Heart caves."),
    (482, "Azelf", "Sinnoh: the lake in the east.",
     "Lake Valor, Lv50. Also in the Test of Heart caves and the Whirl Islands."),
    (483, "Dialga", "Sinnoh: the Lost Artifacts, where time and space began.",
     "Celestic Town during the Lost Artifacts, Lv80 (Dialga or Palkia). The other can be met in the Unown Ruins."),
    (484, "Palkia", "Sinnoh: the Lost Artifacts, where time and space began.",
     "Celestic Town during the Lost Artifacts, Lv80 (Dialga or Palkia). The other can be met in the Unown Ruins."),
    (485, "Heatran", "Sinnoh: a hot chamber inside the great mountain.",
     "Mt. Coronet, Lv30, in the chamber opened from Snowpoint's side via Route 216, after the Sinnoh League."),
    (486, "Regigigas", "Sinnoh: a temple at the foot of the northern mountains.",
     "Regigigas Temple, Lv60."),
    (487, "Giratina", "A world where everything is reversed.",
     "The Distortion World, Lv80. Also one of the four choices in Littleroot when you return the Mega Bracelet."),
    (488, "Cresselia", "It brings good dreams. Look where the moon shines on an island.",
     "Crescent Isle, Lv50. Also met through the Ultra Wormhole on Mt. Pyre."),
    (489, "Phione", "It is never met in the wild. Something must be born.",
     "Hatch it from an Egg: leave Manaphy at the Day Care."),
    (490, "Manaphy", "The deep sea, far below where divers go.",
     "Deep Sea, Lv30 (Dive there)."),
    (491, "Darkrai", "A tower where the dead are honored, full of a dark presence.",
     "The Lost Tower in Sinnoh, Lv50, once the nightmare quest in Solaceon Town is done."),
    (492, "Shaymin", "A paradise of flowers, far from any route.",
     "Flower Paradise, Lv30."),
    (493, "Arceus", "The end of the Lost Artifacts, above the clouds.",
     "Mountain Top, Lv80, with all 17 Plates in your Bag."),
    (494, "Victini", "A city in a crater: the one that brings victory.",
     "Sootopolis City, Lv30."),
    (638, "Cobalion", "A cave road where champions are tested: three swordsmen train there.",
     "Victory Road, Lv70, with Terrakion and Virizion (Blake brought them there to train)."),
    (639, "Terrakion", "A cave road where champions are tested: three swordsmen train there.",
     "Victory Road, Lv70, with Cobalion and Virizion (Blake brought them there to train)."),
    (640, "Virizion", "A cave road where champions are tested: three swordsmen train there.",
     "Victory Road, Lv70, with Cobalion and Terrakion (Blake brought them there to train)."),
    (641, "Tornadus", "A storm spirit. Someone at a Sinnoh wind farm tracks strange weather.",
     "Talk to the researcher at the Valley Windworks in Sinnoh and follow the storm reports."),
    (642, "Thundurus", "A storm spirit. Someone at a Sinnoh wind farm tracks strange weather.",
     "Talk to the researcher at the Valley Windworks in Sinnoh and follow the storm reports."),
    (643, "Reshiram", "Unova: a tower of dragons, reached through a cold town.",
     "Dragonspiral Tower, Lv50, reached through Icirrus Town."),
    (644, "Zekrom", "Unova: a tower of dragons, reached through a cold town.",
     "Dragonspiral Tower, Lv50, reached through Icirrus Town."),
    (645, "Landorus", "A shrine in an ancient Sinnoh town, once both storm spirits are yours.",
     "Celestic Town's shrine, Lv45, with Tornadus and Thundurus in your party."),
    (646, "Kyurem", "Unova: an ice-cold chasm.",
     "Giant Chasm, Lv50. Also one of the four choices in Littleroot when you return the Mega Bracelet."),
    (647, "Keldeo", "A cave road where champions are tested.",
     "Victory Road, Lv30. A tutor teaches it Secret Sword."),
    (648, "Meloetta", "Sinnoh: a stage in the city of hearts.",
     "Hearthome City: it joins you after its performance, Lv50."),
    (649, "Genesect", "Hoenn: a power plant hidden underground.",
     "New Mauville, Lv50."),
    (716, "Xerneas", "Kalos: a forest of life.",
     "Allearth Forest, Lv50. Also one of the four choices in Littleroot when you return the Mega Bracelet."),
    (717, "Yveltal", "Kalos: a lake beside a forest.",
     "Allearth Lake, Lv50. Also one of the four choices in Littleroot when you return the Mega Bracelet."),
    (718, "Zygarde", "Kalos: a cave at the end of the line.",
     "Terminus Cave, Lv70. Zygarde Cells and Prof. Sycamore handle its forms."),
    (719, "Diancie", "Hoenn: an underpass a fossil lover dug himself.",
     "Desert Underpass, Lv30."),
    (720, "Hoopa", "Hoenn: the deepest part of a wrecked ship.",
     "The depths of the Abandoned Ship, Lv50."),
    (721, "Volcanion", "A steaming cave beyond an Ultra Wormhole.",
     "Nebel Cave, Lv50, through the Route 116 wormhole."),
    (772, "Type: Null", "Hoenn: a hidden basement lab in a company's building.",
     "The basement lab under Devon Corp. in Rustboro, Lv50 (behind the receptionist)."),
    (773, "Silvally", "It is never met in the wild. It needs a bond to grow.",
     "Evolve Type: Null with high friendship."),
    (785, "Tapu Koko", "One of four island guardians: the trials of the Kahunas.",
     "Strange Island, Lv50, in the Tapu trials."),
    (786, "Tapu Lele", "One of four island guardians: the trials of the Kahunas.",
     "Strange Island, Lv50, in the Tapu trials. Also in the Safari Zone."),
    (787, "Tapu Bulu", "One of four island guardians: the trials of the Kahunas.",
     "Strange Island, Lv50, in the Tapu trials."),
    (788, "Tapu Fini", "One of four island guardians: the trials of the Kahunas.",
     "Strange Island, Lv50, in the Tapu trials."),
    (789, "Cosmog", "Hoenn: a cave of the dragon clan, and a tower that comes and goes.",
     "Meteor Falls (the Draconid cave) and Mirage Tower, Lv15."),
    (790, "Cosmoem", "It is never met in the wild. Something small must grow.",
     "Evolve Cosmog."),
    (791, "Solgaleo", "It is never met in the wild. It grows under the sun.",
     "Evolve Cosmoem during the day."),
    (792, "Lunala", "It is never met in the wild. It grows under the moon.",
     "Evolve Cosmoem at night."),
    (793, "Nihilego", "Beyond the first Ultra Wormhole, near a town built on the sea.",
     "EV Training Cave, through the Ultra Wormhole near Pacifidlog Town, Lv50. It also appears at Rainbow Castle."),
    (794, "Buzzwole", "Beyond an Ultra Wormhole in a tower that comes and goes.",
     "Ultra Space, through the wormhole in Mirage Tower (also opened from Icirrus Town), Lv50."),
    (795, "Pheromosa", "Beyond an Ultra Wormhole on a mountain of graves.",
     "Ultra Space, through the wormhole on Mt. Pyre (also Crescent Isle, Desert Ruins, Route 210), Lv50."),
    (796, "Xurkitree", "Beyond an Ultra Wormhole in a power plant hidden underground.",
     "Ultra Space, through the wormhole in New Mauville (also the Deep Sea, Remote Island, Cerulean Cave), Lv50."),
    (797, "Celesteela", "Beyond an Ultra Wormhole in an icy cave of the tides.",
     "Ultra Space, through the wormhole in Shoal Cave (also New Mauville, Giant Chasm, Devon's basement), Lv50."),
    (798, "Kartana", "Beyond an Ultra Wormhole on a route near Rustboro City.",
     "Ultra Space, through the wormhole on Route 116 (also Allearth Forest, Faraway Island), Lv50."),
    (799, "Guzzlord", "Beyond an Ultra Wormhole in a dark cave near Dewford.",
     "Ultra Space, through the wormhole in Granite Cave (also Terminus Cave), Lv50."),
    (800, "Necrozma", "The far side of an Ultra Wormhole, after gathering many crystals.",
     "Ultra Space Zero, Lv50, after the 18 Z-Crystals and Faba."),
    (801, "Magearna", "Hoenn: a hidden basement lab in a company's building.",
     "The basement lab under Devon Corp. in Rustboro, Lv30 or Lv50."),
    (802, "Marshadow", "Hoenn: a cave whose Pokemon keep changing.",
     "Altering Cave, Lv30."),
    (803, "Poipole", "Beyond an Ultra Wormhole on a mountain of graves: a gift.",
     "A gift in Ultra Space, through the wormhole on Mt. Pyre, Lv5."),
    (804, "Naganadel", "It is never met in the wild. Something small must grow.",
     "Evolve Poipole."),
    (805, "Stakataka", "Beyond an Ultra Wormhole in a cave of the dragon clan.",
     "Ultra Space, through the wormhole in Meteor Falls (also Mt. Silver), Lv70."),
    (807, "Zeraora", "Lightning in a Sinnoh city, and in a castle of rainbows.",
     "Eterna City, Lv50. Also met in Rainbow Castle."),
    (808, "Meltan", "Hoenn: someone in a seaside city has a small metal gift.",
     "A gift in Lilycove City, Lv5."),
    (809, "Melmetal", "It is never met in the wild. Something small must grow.",
     "Evolve Meltan."),
    (888, "Zacian", "Sinnoh: an island of iron, where heroes of a far land rest.",
     "Iron Island, Lv50."),
    (889, "Zamazenta", "Sinnoh: an island of iron, where heroes of a far land rest.",
     "Iron Island, Lv50."),
    (890, "Eternatus", "The far side of an Ultra Wormhole.",
     "Ultra Space, Lv50."),
    (891, "Kubfu", "Hoenn: a gift where the strongest battle.",
     "A gift at the Battle Frontier, Lv5 (Kubfu or Rockruff)."),
    (892, "Urshifu", "It is never met in the wild. Something small must train.",
     "Evolve Kubfu."),
    (893, "Zarude", "Sinnoh: a town of flowers.",
     "Floaroma Town, Lv50."),
    (894, "Regieleki", "Ruins where one of two choices must be made.",
     "Ruins of Decision, Lv50."),
    (895, "Regidrago", "Ruins where one of two choices must be made.",
     "Ruins of Decision, Lv50."),
    (896, "Glastrier", "A shrine of a crowned king.",
     "Crown Shrine, Lv50. Also a gift choice in Lilycove City (Lv15)."),
    (897, "Spectrier", "A shrine of a crowned king.",
     "Crown Shrine, Lv50. Also a gift choice in Lilycove City (Lv15)."),
    (898, "Calyrex", "A shrine of a crowned king.",
     "Crown Shrine, Lv50."),
    (905, "Enamorus", "Hisui: a legend Cogita tells, once the storm spirits are yours.",
     "Hisui, Lv50, after showing Cogita Tornadus, Thundurus and Landorus. The God of Forms waits at the Moonbow Dome (Lv70)."),
]

assert [d for d, *_ in LEGENDS] == sorted(d for d, *_ in LEGENDS), "keep them in National Dex order"
assert len({d for d, *_ in LEGENDS}) == len(LEGENDS)
