"""The Quest Log's Side Content chapter: optional content outside the Journal's story, from the content audit
(tools/romdata/flag_audit.py, docs/content-audit.html). Each row is ticked by the flag its own script sets.

Each row: (flag, name, where). Names are always shown; A shows where.
"""

SIDE = [
    # ---- Hisuian trades: people who slipped through time
    (0x0099, "Hisuian Zorua trade",
     "Rustboro City: someone a gift fox turned into something else trades their Hisuian Zorua."),
    (0x4327, "Hisuian Voltorb trade",
     "Mauville City: a researcher of how time changes Pokémon trades a Hisuian Voltorb."),
    (0x4328, "Hisuian Growlithe trade",
     "Lavaridge Town: a traveller who remembers only Hisui trades their Hisuian Growlithe."),
    (0x009B, "Hisuian Sneasel trade",
     "Fortree City: a traveller through time and space trades a Hisuian Sneasel."),
    (0x009A, "Hisuian Qwilfish trade",
     "Safari Zone: a fisherman looking for a needle fish trades a Hisuian Qwilfish."),
    (0x4329, "White-Striped Basculin",
     "Route 119: someone who dreamed of feeding the Phantom Fish trades a White-Striped Basculin."),
    # ---- gift Pokémon
    (0x4311, "A legendary choice",
     "Littleroot Town: return the Mega Bracelet at home for a choice of Giratina, Kyurem, Xerneas or Yveltal."),
    (0x4055, "Meloetta",
     "Hearthome City: it joins you after its performance on stage, Lv50."),
    (0x40B9, "A Galar gift",
     "Lilycove City: a choice of Galar Pokémon (Corsola, Eiscue, Glastrier, Indeedee, Morpeko, Mr. Mime...), Lv15."),
    (0x40CA, "Meltan",
     "Lilycove City: a gift, Lv5."),
    (0x40F2, "Kubfu or Rockruff",
     "Battle Frontier: a gift, Lv5."),
    (0x41BD, "Poipole",
     "Ultra Space, through the Ultra Wormhole on Mt. Pyre: a gift, Lv5."),
    (0x41B7, "Wimpod",
     "Timeless Woods: a gift, Lv10."),
    (0x4307, "Let's Go partner",
     "Hearthome City (also the Bell Tower): Let's Go Eevee or Pikachu, Lv5."),
    (0x408F, "Pikachu Belle",
     "Lavaridge Town: a gift, Lv5."),
    (0x010B, "A revived fossil",
     "Rustboro City: Devon Corp. revives a fossil of your choice, Lv20."),
    (0x42DE, "Drifloon",
     "Valley Windworks in Sinnoh: a gift, Lv15."),
    (0x4118, "Magikarp",
     "Route 210 in Sinnoh: a gift, Lv1."),
    (0x012A, "Beldum",
     "Mossdeep City: in Steven's house, Lv5."),
    # ---- starters from other regions, hidden one-off battles
    (0x045D, "Snivy",
     "Petalburg Woods: a hidden one-off battle, Lv5."),
    (0x044D, "Oshawott",
     "The Abandoned Ship: a hidden one-off battle, Lv21."),
    (0x0415, "Litten",
     "Meteor Falls: a hidden one-off battle, Lv5."),
    (0x40B8, "Grookey",
     "Mt. Silver: a hidden one-off battle, Lv5."),
    (0x40EA, "Scorbunny",
     "Lake of Despair: a hidden one-off battle, Lv5."),
    (0x4189, "Chespin",
     "Remote Island: a hidden one-off battle, Lv5."),
    (0x4321, "Chikorita",
     "Timeless Woods: a hidden one-off battle, Lv5."),
    (0x41C6, "Cyndaquil",
     "The Bell Tower in Johto: a hidden one-off battle, Lv5."),
    (0x4088, "Totodile",
     "The Whirl Islands in Johto: a hidden one-off battle, Lv5."),
    # ---- side stories
    (0x42A3, "Red, Blue and Buzzwole",
     "Route 102: Red and Blue corner an Ultra Beast at an Ultra Wormhole."),
    (0x42B7, "The Shadow Triad",
     "Shoal Cave: Tate and Liza hold off the Shadow Triad. Take the last one."),
    (0x41DF, "A voice in Terra Cave",
     "Terra Cave: a familiar voice battles someone who controls the sunlight."),
    (0x41DE, "A voice in Marine Cave",
     "Marine Cave: a familiar voice battles someone who controls the rain."),
    (0x42B3, "Trouble in New Mauville",
     "New Mauville: someone is behind the generator trouble."),
    (0x4165, "The woods' mentor",
     "Petalburg Woods: a mysterious trainer who teaches you about battles."),
    (0x42A7, "The lost Skitty",
     "Mauville City: find the lady's Skitty and bring it home."),
    (0x4264, "The bike exam",
     "Mauville City: pass the cycling exam (Renli in Eterna City has a bike shop too)."),
    (0x40CE, "Lucas and Barry",
     "The Sinnoh League: your Sinnoh friends greet you. Barry waits in Twinleaf Town for a battle."),
    (0x4269, "The chateau's TV",
     "The Old Chateau in Sinnoh: watch the TV closely."),
    (0x432D, "The cursed statue",
     "The Old Chateau in Sinnoh: a powerful grudge dwells in a statue."),
    # ---- hidden powers: the Burning Soul and the Hero Greninja (Ash's Koga ninja style)
    (0x4301, "The Burning Soul",
     "Route 112, foot of Mt. Chimney (west): a hidden cave. Take TM53, face the flame creature and stay. "
     "ONE try: the cave collapses after. Win 3 rounds for the Burning Soul, as a Typhlosion trainer once did."),
    (0x42FF, "Koga's mark",
     "Champion Island: battle Koga of Johto's Elite Four. He gives you his mark and tells of a hidden ninja "
     "village reached through the forest of Route 102."),
    (0x4300, "The Hero Greninja",
     "Koga's Village, through the Route 102 forest: bring only one Greninja to Elder Koga's two-stage trial "
     "(some items are banned). Your Greninja gains its hero form, like Ash's."),
    (0x4302, "Ash's challenge",
     "Route 101: once your Greninja has its hero form, Ash from Pallet Town comes to battle. A red-haired "
     "passerby joins in, and leaves a note behind."),
    (0x4303, "The note's sender",
     "Steven's Island: the northeast corner of Steven's residence. The passerby from Route 101 is waiting."),
]

assert len({f for f, *_ in SIDE}) == len(SIDE)
assert all(len(n) <= 24 for _, n, _ in SIDE)
